import '../../domain/models/legal_section.dart';
import 'app_strings.dart';

/// Structured copy for the three static info documents plus the FAQ —
/// broken into headings/paragraphs/bullets so [LegalInfoScreen] and
/// [FaqScreen] can render real typographic hierarchy instead of one long
/// block of plain text.
class LegalContent {
  LegalContent._();

  static const String lastUpdated = 'Last updated: July 2026';

  static const String privacyIntro =
      'TripNest PH ("we", "our", "the app") helps you discover tourist spots, restaurants, and festivals across the Philippines, and lets you save favorites, write reviews, and build trip itineraries.';

  static const List<LegalSection> privacySections = [
    LegalSection(
      heading: 'Information we collect',
      bullets: [
        'Account details you provide when you register: name, email address, and profile photo.',
        'Content you create: favorites, saved itineraries, reviews, ratings, and review photos.',
        'Device information used to enable features you turn on, such as your approximate location (for "Nearby You" recommendations) and a push-notification token (for trip and festival alerts).',
      ],
    ),
    LegalSection(
      heading: 'How we use it',
      paragraph:
          'Your data is used only to run the app\'s features described above — personalizing recommendations, syncing your favorites and itineraries across sessions, and showing your reviews to other users. We do not sell your personal information to third parties.',
    ),
    LegalSection(
      heading: 'Where it\'s stored',
      paragraph:
          'Account data, favorites, itineraries, and reviews are stored securely in Firebase (Google Cloud) under your account and protected by access rules that only allow you to read and write your own data. Photos you upload are stored in Firebase Storage.',
    ),
    LegalSection(
      heading: 'Your choices',
      paragraph:
          'You can edit or delete your profile information, remove any review or saved itinerary, and disable location or notification permissions at any time from Settings or your device\'s system settings. Deleting your account removes your personal data from our records.',
    ),
    LegalSection(heading: 'Contact us', paragraph: 'Questions about this policy can be sent to privacy@tripnestph.app.'),
  ];

  static const String termsIntro = 'By creating an account or using TripNest PH, you agree to these terms.';

  static const List<LegalSection> termsSections = [
    LegalSection(
      heading: 'Using the app',
      paragraph:
          'TripNest PH is a travel discovery and planning tool. It is not a booking platform — the app does not process payments, reservations, or bookings on your behalf. Contact details, links, and pricing shown for destinations, restaurants, and festivals are provided for reference and may change without notice; always confirm details directly with the venue or organizer before traveling.',
    ),
    LegalSection(
      heading: 'Your account',
      paragraph:
          'You\'re responsible for keeping your login credentials secure and for the accuracy of the information you provide. You must be at least 13 years old to create an account.',
    ),
    LegalSection(
      heading: 'User-generated content',
      paragraph:
          'When you post a review, rating, or photo, you confirm it\'s your own honest experience and that you have the right to share any photos you upload. We may remove content that is abusive, misleading, or violates these terms.',
    ),
    LegalSection(
      heading: 'AI-assisted features',
      paragraph:
          'Itinerary suggestions generated by the app\'s planning tools are provided for inspiration only. They are not guarantees of availability, pricing, weather, or safety conditions — always verify details before finalizing travel plans.',
    ),
    LegalSection(
      heading: 'Availability',
      paragraph:
          'We aim to keep TripNest PH available and accurate, but the app is provided "as is" without warranties of any kind. We may update, suspend, or discontinue features at any time.',
    ),
    LegalSection(
      heading: 'Changes to these terms',
      paragraph: 'We may update these terms as the app evolves. Continued use after a change means you accept the updated terms.',
    ),
    LegalSection(heading: 'Contact us', paragraph: 'Questions about these terms can be sent to support@tripnestph.app.'),
  ];

  static const String aboutIntro =
      'TripNest PH is your companion for exploring the Philippines — from postcard-famous beaches to hidden waterfalls, family-run carinderias to festival street parties.';

  static const List<String> aboutFeatures = [
    'Browse curated tourist spots, restaurants, and festivals from all over the country.',
    'Search and filter by province, category, and rating.',
    'Save your favorite places and build itineraries for upcoming trips.',
    'Rate and review places you\'ve visited, with photos.',
    'Get AI-assisted trip planning suggestions tailored to your interests.',
  ];

  static const String aboutClosing =
      'Built for Filipino travelers and visitors alike, ${AppStrings.appName} is designed to make discovering the country\'s 7,000+ islands feel a little more personal.';

  static const String appVersion = 'Version 1.0.0';
  static const String aboutFooter = 'Made with care in the Philippines.';

  /// Canonical display order for FAQ section headers — categories not in
  /// this list (there shouldn't be any) sort after everything here.
  static const List<String> faqCategoryOrder = [
    'Getting Started',
    'Account & Profile',
    'Trip Planning & AI',
    'Reviews & Photos',
    'Privacy & Location',
    'Support',
  ];

  static const List<FaqItem> faq = [
    // Getting Started
    FaqItem(
      category: 'Getting Started',
      question: 'Is TripNest PH free to use?',
      answer: 'Yes. Browsing destinations, saving favorites, writing reviews, and using the AI trip planner are all free.',
    ),
    FaqItem(
      category: 'Getting Started',
      question: 'Do I need an account to use the app?',
      answer:
          'You can browse destinations, restaurants, and festivals without one. You\'ll need an account to save favorites, write reviews, or build and save itineraries.',
    ),
    FaqItem(
      category: 'Getting Started',
      question: 'Can I book hotels, restaurants, or festival tickets through the app?',
      answer:
          'Not directly — TripNest PH is a discovery and planning tool, not a booking platform. Contact details, links, and pricing shown are for reference; always confirm with the venue or organizer directly before traveling.',
    ),
    FaqItem(
      category: 'Getting Started',
      question: 'How do I find places near me?',
      answer:
          'The "Nearby You" section on Home shows destinations and restaurants closest to your current location, once you\'ve allowed location access.',
    ),
    FaqItem(
      category: 'Getting Started',
      question: 'How do I search for a specific place?',
      answer: 'Tap the search bar on Home or Explore and type a destination, restaurant, or festival name. You can also filter by province and rating.',
    ),
    // Account & Profile
    FaqItem(
      category: 'Account & Profile',
      question: 'How do I change my profile photo or name?',
      answer: 'Go to Profile → Edit Profile to update your name and photo. If you signed in with Google, your Google profile photo is used by default.',
    ),
    FaqItem(
      category: 'Account & Profile',
      question: 'How do I change the app language?',
      answer: 'Go to Settings → Language and choose between English and Filipino. The switch applies immediately.',
    ),
    FaqItem(
      category: 'Account & Profile',
      question: 'I forgot my password. What do I do?',
      answer: 'On the login screen, tap "Forgot Password" and enter your registered email — we\'ll send you a reset link.',
    ),
    FaqItem(
      category: 'Account & Profile',
      question: 'How do I delete my account?',
      answer:
          'Email support@tripnestph.app from your registered email address to request account deletion. This removes your personal data, favorites, itineraries, and reviews from our records.',
    ),
    FaqItem(
      category: 'Account & Profile',
      question: 'Can I use TripNest PH on more than one device?',
      answer: 'Yes — sign in with the same account and your favorites, itineraries, and reviews stay in sync across devices.',
    ),
    // Trip Planning & AI
    FaqItem(
      category: 'Trip Planning & AI',
      question: 'How accurate are the AI-generated itineraries?',
      answer:
          'They\'re a starting point for inspiration, built from your interests and trip details. They\'re not guarantees of availability, pricing, weather, or safety — always double-check details before finalizing plans.',
    ),
    FaqItem(
      category: 'Trip Planning & AI',
      question: 'How do I save a destination or itinerary?',
      answer:
          'Tap the bookmark icon on any destination, restaurant, or festival card to save it to your favorites. Itineraries generated by the AI Planner can be saved from the itinerary screen and revisited anytime under Saved.',
    ),
    FaqItem(
      category: 'Trip Planning & AI',
      question: 'Can I edit an itinerary after the AI generates it?',
      answer: 'Yes — you can regenerate it with different preferences, or remove individual stops before saving it.',
    ),
    FaqItem(
      category: 'Trip Planning & AI',
      question: 'What can I ask the AI Travel Assistant?',
      answer:
          'Anything trip-related — recommendations by province or interest, festival timing, budget-friendly ideas, or help refining a saved itinerary. Tap the chat icon on any tab to open it.',
    ),
    FaqItem(
      category: 'Trip Planning & AI',
      question: 'Does the AI Planner know real-time prices or availability?',
      answer: 'No — it doesn\'t have live pricing or booking data. Treat its suggestions as a planning starting point and confirm details directly with venues.',
    ),
    // Reviews & Photos
    FaqItem(
      category: 'Reviews & Photos',
      question: 'Can I edit or delete a review I posted?',
      answer: 'Yes — open the review from your Profile and you\'ll find options to edit or delete it there.',
    ),
    FaqItem(
      category: 'Reviews & Photos',
      question: 'Can I add photos to my review?',
      answer: 'Yes — when writing a review you can attach photos from your device to show other travelers what to expect.',
    ),
    FaqItem(
      category: 'Reviews & Photos',
      question: 'Why was my review removed?',
      answer: 'Reviews that are abusive, misleading, or unrelated to a genuine visit may be removed to keep listings trustworthy for other travelers.',
    ),
    FaqItem(
      category: 'Reviews & Photos',
      question: 'I found incorrect information on a listing. What should I do?',
      answer:
          'Please email support@tripnestph.app with the destination/restaurant/festival name and what\'s wrong — our team reviews and corrects listings regularly.',
    ),
    // Privacy & Location
    FaqItem(
      category: 'Privacy & Location',
      question: 'Why does the app ask for my location?',
      answer:
          'Location is only used for the "Nearby You" recommendations on Home, so you can see what\'s close by. You can turn this off anytime in Settings without losing any other functionality.',
    ),
    FaqItem(
      category: 'Privacy & Location',
      question: 'Does TripNest PH sell my data?',
      answer: 'No. Your data is used only to run the app\'s own features — see our Privacy Policy for the full details.',
    ),
    FaqItem(
      category: 'Privacy & Location',
      question: 'Can I turn off notifications?',
      answer: 'Yes — go to Settings and toggle Notifications off. You can turn festival alerts and trip reminders back on anytime.',
    ),
    FaqItem(
      category: 'Privacy & Location',
      question: 'Where is my data stored?',
      answer: 'Your account data, favorites, itineraries, and reviews are stored securely in Firebase (Google Cloud), protected by access rules scoped to your account.',
    ),
    // Support
    FaqItem(
      category: 'Support',
      question: 'The app is showing an error or won\'t load. What should I do?',
      answer: 'Check your internet connection first, then try closing and reopening the app. If it still doesn\'t work, email support@tripnestph.app with a description of what happened.',
    ),
    FaqItem(
      category: 'Support',
      question: 'How do I contact support?',
      answer: 'Email support@tripnestph.app for general help, or privacy@tripnestph.app for privacy-specific questions. We aim to reply within a few business days.',
    ),
    FaqItem(
      category: 'Support',
      question: 'Can I suggest a destination, restaurant, or festival to add?',
      answer: 'Yes — email support@tripnestph.app with details and photos if you have them. Suggestions are reviewed by our local tourism partners.',
    ),
  ];
}
